using ICD.Connect.Audio.Biamp.Tesira.TesiraTextProtocol.Parsing;
using NUnit.Framework;

namespace ICD.Connect.Audio.Biamp.Tests.TesiraTextProtocol.AttributeInterfaces.IoBlocks.TelephoneInterface
{
	[TestFixture]
	public sealed class TiControlStatusBlockTest
	{
		[Test]
		public void FeedbackParsingTest()
		{
			const string ttp = @"! ""PUBLISHTOKEN"":""VDC - CALLSTATE - "" ""VALUE"":{""CALLSTATEINFO"":[{""STATE"":VOIP_CALL_STATE_BUSY ""LINEID"":0 ""CALLID"":0 ""ACTION"":UI_DISPLAY_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_TEMP_UNAVAILABLE} {""STATE"":VOIP_CALL_STATE_IDLE ""LINEID"":0 ""CALLID"":1 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_NONE} {""STATE"":VOIP_CALL_STATE_IDLE ""LINEID"":0 ""CALLID"":2 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_NONE} {""STATE"":VOIP_CALL_STATE_IDLE ""LINEID"":0 ""CALLID"":3 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_NONE} {""STATE"":VOIP_CALL_STATE_IDLE ""LINEID"":0 ""CALLID"":4 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_NONE} {""STATE"":VOIP_CALL_STATE_IDLE ""LINEID"":0 ""CALLID"":5 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_NONE} {""STATE"":VOIP_CALL_STATE_INIT ""LINEID"":1 ""CALLID"":0 ""ACTION"":UI_DISPLAY_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_SIP_USER_NOT_CONFIGURED} {""STATE"":VOIP_CALL_STATE_INIT ""LINEID"":1 ""CALLID"":1 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_SIP_USER_NOT_CONFIGURED} {""STATE"":VOIP_CALL_STATE_INIT ""LINEID"":1 ""CALLID"":2 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_SIP_USER_NOT_CONFIGURED} {""STATE"":VOIP_CALL_STATE_INIT ""LINEID"":1 ""CALLID"":3 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_SIP_USER_NOT_CONFIGURED} {""STATE"":VOIP_CALL_STATE_INIT ""LINEID"":1 ""CALLID"":4 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_SIP_USER_NOT_CONFIGURED} {""STATE"":VOIP_CALL_STATE_INIT ""LINEID"":1 ""CALLID"":5 ""ACTION"":UI_CLEAR_STATUS ""CID"":"""" ""PROMPT"":VOIP_PROMPT_SIP_USER_NOT_CONFIGURED}]}";

			Assert.DoesNotThrow(() => TtpUtils.DeserializeValue(ttp));
		}
	}
}
